### ISSUE TITLE
VS 2015 & VS2017 Support

### ISSUE THREAD

**Issue by thenrich2009** [nbasakuragi/LINQBridgeVs#27]
I hope to see VS 2015 & VS 2017 support

**Comment by amellini** [comment]
So?
There's plan to support vs2017?

**Comment by nbasakuragi** [comment]
There is, I'm currently working on supporing VS2015 and VS2017

**Comment by CSharpByDesign** [comment]
Really enjoy this tool and hope you're able to get it taken care of soon !

**Comment by nbasakuragi** [comment]
Added support for VS 2015. Will work on adding 2017 support

**Comment by CSharpByDesign** [comment]
@nbasakuragi Thank you!!  Really looking forward to being able to debug via this method again.. Moles works, but not nearly as well.

**Comment by nbasakuragi** [comment]
Added 2017 support, a new vsix installer will come out soon in the vs marketplace
